### ISSUE TITLE
mate install <repo url>

### ISSUE THREAD

**Issue by SalamanderXing** [ilex-paraguariensis/yerbamate#10]
Allows to install models from repos

**Comment by SalamanderXing** [comment]
- Install or add now doesn't handle training classes (base models) yet. 
- Also hyperparameters should be automatically generated to avoid redundancy -> bugs. Also one cannot define in a json all the hyperparameters in all the (possibly sub-) models in a mate project, which is needed for the following.
- Also one should be able to install an arbitrary model from an arbitrary repo. Add now is great but not complete.

**Comment by oalee** [comment]
I agree that parameters should be automatically generated, but sub-modules parameters in a json would be redundant and unnecessary, not all the modules need to have hyperparameters in a json, for example, a conv2dblock does not need its hyperparameters to be present in a json file, instead, the parent class should handle its child parameters. 


> Also one should be able to install an arbitrary model from an arbitrary repo.

I don't know if its best to separate the models so that each repo has only one or allow multiple models to be in one repo. We could use branches to handle this, each branch can have a specific model, and the main branch can have all the models.

**Comment by SalamanderXing** [comment]
> I agree that parameters should be automatically generated, but sub-modules parameters in a json would be redundant and unnecessary, not all the modules need to have hyperparameters in a json, for example, a conv2dblock does not need its hyperparameters to be present in a json file, instead, the parent class should handle its child parameters.

Indeed, I mean we shouldn't do that! I meant that would be necessary to publish all of the sub-modules. Not for installing a parent model (which as you said chooses the children hyperparameters).

> I don't know if its best to separate the models so that each repo has only one or allow multiple models to be in one repo. We could use branches to handle this, each branch can have a specific model, and the main branch can have all the models.

Yes but then once you created your project with all your models you'd have to create one branch per model! 
Actively publishing should be a feature necessary only for model weights, not for model source code. If it takes additional work to publish something people won't do it and one of the coolest features of mate will be useless.

**Comment by oalee** [comment]
Agreed, export should be out-of-the-box, at most with just one command, something like `mate export model component`.
I was just concerned about the size of cloning the whole project that can become big sometimes, that's why I suggested to maybe have a branch called mate that only has exports (which could be automatic with mate export command)
