### ISSUE TITLE
Fix dependecies

### ISSUE THREAD

**Issue by SalamanderXing** [ilex-paraguariensis/yerbamate#16]
Installing mate does not install properly its dependencies

**Comment by oalee** [comment]
we need to think how to manage pytorch, python and other dependency versions. an easy solution would be with conda environments, a harder solution would be making everything work with the latest pytorch version and always support latest.
we can't have pip dependencies since we need to internally manage dependencies for models with cuda/torch versions.

**Comment by oalee** [comment]
since mate requires python 3.9, we should support everything on the last version
