### ISSUE TITLE
Results should be decoupled from models implementation. 

### ISSUE THREAD

**Issue by SalamanderXing** [ilex-paraguariensis/yerbamate#28]
This way you can train in one directory and save results on an external disk for example.

**Comment by oalee** [comment]
now you can use `--output=path` to specify the output path. This will set the output path as the root path for all results of your models and parameters (better for restarting and saving different models without changing the output).

**Comment by SalamanderXing** [comment]
Since the output is valid globally, now I added a mandatory `results_folder=path` to mate.json instead.

**Comment by SalamanderXing** [comment]
Also now if mate finds results in the project folder (and this is not the results_folder) it will move them to the correct location. 
Basically this means that you can update results_folder and mate will update your project.

**Comment by oalee** [comment]
> Basically this means that you can update results_folder and mate will update your project.

How does mate know what the previous result folder was? If by previous result you mean inside the model folder, this will only work a few times and the function would not ever get called again.

Since the field is mandatory now, by default we can assign "results" as the main result folder if not assigned (or in default mate.json)

**Comment by ilex-paraguariensis** [comment]
It doesn't, it just checks if it is in the models/<model name>/results. This feature is useful from migrating from one version to another, or if you start off with a small project and don't care about different folder but then when you can't push any more due to sizes (as it is happening to me) you need to do this. 

Yeah sure.

**Comment by oalee** [comment]
By defaulting results to a separate folder alongside the root_projet folder we won't have this issue anymore. That said this feature of automatically moving results from model folders to somewhere else was only required once because we're changing the design, and we should not keep that code in Mate class as it won't be used anymore after this update.

Instead of doing these things inside Mate class, we should implement a different way to handle migration issues rather than changing something inside Mate class. We should keep record of mate version, and always after updating mate, call required migrators to handle any issue, this way we separated concerns of what should be responsibilities of Mate class and migration issues.

**Comment by SalamanderXing** [comment]
In general, I super agree about a separate version manager. However, in mate, we also need a way to migrate the results (keeping the same version). Doing it by hand for all models is very tedious.

**Comment by oalee** [comment]
I see it as a chicken and egg problem, if we want to decouple the results from models then we might encounter inconsistencies, but without any decoupling we have this issue of exploding project size, we don't want to commit large models that are experimental.
For reproducibility, the models should be coupled with results, but during experiments, we can decouple the results from models.

That said, we have yet to design a system for pretrained models, pretrained models are if fact coupled with specific models (and parameters). We need to design a system for loading such pretrained models and make our framework suitable for transfer learning.  This leads to issues of handling of large files as pretrained models can become quite large, terabytes even! and we have to handle versioning as well.

**Comment by SalamanderXing** [comment]
Well, the large files are just the pre-trained models. If we want we could keep all the other results coupled. But keeping the pre-trained models is simply not an option so we just have to do it well.

We should handle sharing of pre-trained models in a new issue (do we actually need versioning?).

**Comment by oalee** [comment]
> Well, the large files are just the pre-trained models. If we want we could keep all the other results coupled. But keeping the pre-trained models is simply not an option so we just have to do it well.

You're right. We should decouple, but then snapshotting a model would also require snapshotting the decoupled result as well.

> We should handle sharing of pre-trained models in a new issue (do we actually need versioning?).

We need this for two scenarios, first, in case of model upgrades and secondly in case of just weight upgrade, for example I'm training a large model, lets say Imogen or dall-e, it takes a long time to train those and after a few days of more training the user might want to publish the model again

**Comment by SalamanderXing** [comment]
But don't we have re-upload all the model weights in both cases? Both if we changed the model and if we changed the weights?
Anyways maybe we could continue this in its own [issue](https://github.com/ilex-paraguariensis/yerbamate/issues/35).
